services:
  file-storage:
    image: file-storage:latest
    restart: unless-stopped
    volumes:
      - ./src:/src
      - ${ROOT_FOLDER}:${ROOT_FOLDER}
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env
    depends_on:
      - file-storage-db
    networks:
      - app-network

  file-storage-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_FOLDER}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge