FROM python:3.10
WORKDIR /app
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt
RUN pip install -r requirements-dev.txt
COPY ./app /app/app
COPY ./tests /app/tests
EXPOSE 5001
ENV PYTHONPATH=/app/app
CMD ["pytest", "-s"]