version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    restart: always
    volumes:
      - ./app:/app
      - ${ROOT_FOLDER}:/root_folder
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - ROOT_FOLDER=${ROOT_FOLDER}
  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"