services:
  file-storage:
    image: file-storage:latest
    restart: unless-stopped
    volumes:
      - /root_folder:/root_folder
    ports:
      - "5000:80"
    env_file:
      - .env

  file-storage-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"